apiVersion: v1
kind: ResourceQuota 
metadata:
  name: resourcequota
  namespace: default
spec:
  hard:
    pods: "5"
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
 
