apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: mysql
  namespace: default

spec:
  serviceName: db-svc
  replicas: 1

  selector:
    matchLabels:
      app: app-db

  template:
    metadata:
      labels:
        app: app-db

    spec:
      containers:
        - name: db-cont
          image: sukumar722/php:db-image

          ports:
            - containerPort: 3306

          envFrom:
            - secretRef:
                name: bankapp-db-secret

          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "500m"

          volumeMounts:
            - name: pvc-1
              mountPath: /var/lib/mysql

  volumeClaimTemplates:
    - metadata:
        name: pvc-1

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 2Gi
